/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting.index'
import { Route as AppAccountingLedgerRouteImport } from './routes/_app/accounting.ledger'
import { Route as AppAccountingJournalsRouteImport } from './routes/_app/accounting.journals'
import { Route as AppAccountingEntriesRouteImport } from './routes/_app/accounting.entries'
import { Route as AppAccountingChartRouteImport } from './routes/_app/accounting.chart'
import { Route as AppAccountingBalanceRouteImport } from './routes/_app/accounting.balance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingLedgerRoute = AppAccountingLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingJournalsRoute = AppAccountingJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingEntriesRoute = AppAccountingEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingChartRoute = AppAccountingChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingBalanceRoute = AppAccountingBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppAccountingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/accounting/balance': typeof AppAccountingBalanceRoute
  '/accounting/chart': typeof AppAccountingChartRoute
  '/accounting/entries': typeof AppAccountingEntriesRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/ledger': typeof AppAccountingLedgerRoute
  '/accounting/': typeof AppAccountingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/accounting/balance': typeof AppAccountingBalanceRoute
  '/accounting/chart': typeof AppAccountingChartRoute
  '/accounting/entries': typeof AppAccountingEntriesRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/ledger': typeof AppAccountingLedgerRoute
  '/accounting': typeof AppAccountingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounting': typeof AppAccountingRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/accounting/balance': typeof AppAccountingBalanceRoute
  '/_app/accounting/chart': typeof AppAccountingChartRoute
  '/_app/accounting/entries': typeof AppAccountingEntriesRoute
  '/_app/accounting/journals': typeof AppAccountingJournalsRoute
  '/_app/accounting/ledger': typeof AppAccountingLedgerRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounting'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/accounting/balance'
    | '/accounting/chart'
    | '/accounting/entries'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/onboarding'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/accounting/balance'
    | '/accounting/chart'
    | '/accounting/entries'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/accounting'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/onboarding'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/accounting/balance'
    | '/_app/accounting/chart'
    | '/_app/accounting/entries'
    | '/_app/accounting/journals'
    | '/_app/accounting/ledger'
    | '/_app/accounting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/ledger': {
      id: '/_app/accounting/ledger'
      path: '/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AppAccountingLedgerRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/journals': {
      id: '/_app/accounting/journals'
      path: '/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AppAccountingJournalsRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/entries': {
      id: '/_app/accounting/entries'
      path: '/entries'
      fullPath: '/accounting/entries'
      preLoaderRoute: typeof AppAccountingEntriesRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/chart': {
      id: '/_app/accounting/chart'
      path: '/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AppAccountingChartRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/balance': {
      id: '/_app/accounting/balance'
      path: '/balance'
      fullPath: '/accounting/balance'
      preLoaderRoute: typeof AppAccountingBalanceRouteImport
      parentRoute: typeof AppAccountingRoute
    }
  }
}

interface AppAccountingRouteChildren {
  AppAccountingBalanceRoute: typeof AppAccountingBalanceRoute
  AppAccountingChartRoute: typeof AppAccountingChartRoute
  AppAccountingEntriesRoute: typeof AppAccountingEntriesRoute
  AppAccountingJournalsRoute: typeof AppAccountingJournalsRoute
  AppAccountingLedgerRoute: typeof AppAccountingLedgerRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
}

const AppAccountingRouteChildren: AppAccountingRouteChildren = {
  AppAccountingBalanceRoute: AppAccountingBalanceRoute,
  AppAccountingChartRoute: AppAccountingChartRoute,
  AppAccountingEntriesRoute: AppAccountingEntriesRoute,
  AppAccountingJournalsRoute: AppAccountingJournalsRoute,
  AppAccountingLedgerRoute: AppAccountingLedgerRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
}

const AppAccountingRouteWithChildren = AppAccountingRoute._addFileChildren(
  AppAccountingRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
